### ISSUE TITLE
「未定義の筆画の種類」に検出漏れ？

### ISSUE THREAD

**Issue by ge9** [kurgm/gwv#5]
現在、「未定義の筆画の種類」のところに、第1パラメータに手動で100が加算されているとみられる
[u737b-02](https://glyphwiki.org/wiki/u737b-02)
[u737b-02-var-001](https://glyphwiki.org/wiki/u737b-02-var-001)
[u737b-02-var-002](https://glyphwiki.org/wiki/u737b-02-var-002)
の3つが表示されていないようなのですが、これはバグでしょうか？
似た字形の
[u737b-02-var-005](https://glyphwiki.org/wiki/u737b-02-var-005)
は表示されています。
もしかしたら「0:0:0:0」の行以降の不正データが検出されていないかもしれません。

**Comment by kurgm** [comment]
ご報告ありがとうございます！

今は、原則として1つの大項目（「不正なデータ」など）につき最大1個の問題しか検出できない仕様になっています。

u737b-02 (@3) の場合、~4行目~<ins>7行目</ins>の検査で「ありえない形状の組み合わせ」に引っ掛かってしまうため~5行目~<ins>8行目</ins>の検査に辿り着かないので、「未定義の筆画の種類」のグリフリストに現れていません。（したがって、「ありえない形状の組み合わせ」のグリフリストの方には u737b-02 が現れます。）ほか2つも（確認していませんが）同様と思います。

このような仕様にしてある積極的な理由は無いので、修正したい対象ではあります。（単純に手が回っていない / 下準備のリファクタリングで止まっている状態です…）

**Comment by ge9** [comment]
なるほど、そういうことでしたか！
ちなみにgwvは手元でUCSの漢字・IVDの不正データ検出に活用させていただいております。ありがとうございます。
お時間のあるときに修正・機能拡張などお待ちしております！

**Comment by kurgm** [comment]
0f32c7ef4aeedf92536ecaa64b20ae9fc3be35b4 で修正したので、今日の更新分から[「未定義の筆画の種類」の一覧](https://kurgm.github.io/gwv-view/#/illegal/0?filter=%7B%22q%22%3A%22u737b-02%22%7D)にも[「ありえない形状の組み合わせ」の一覧](https://kurgm.github.io/gwv-view/#/illegal/6?filter=%7B%22q%22%3A%22u737b-02%22%7D)にも u737b-02 が表示されるようになりました。
